[package]
name = "zap_lang"
version = "0.1.0"
edition = "2024"

[lib]
name = "zap_lang"
path = "src/lib.rs"

[[bin]]
name = "zap_lang"
path = "src/main.rs"

[build-dependencies] 
lalrpop = "0.22.1"

[dependencies]
lalrpop-util = { version = "0.21.0", features = ["lexer", "unicode"] }
